name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Make sure to update build.sbt when updating this list
        scala: [ "3.3.3", "2.13.14", "2.12.19", "2.11.12" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Run tests
        run: sbt coverage "++${{ matrix.scala }} test"
      - name: Upload coverage data to Coveralls
        run: sbt ++${{ matrix.scala }} coverageReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}